### PR TITLE
[NET-4904] security: update Envoy to 1.26.4

### PR DESCRIPTION
**Pull request by zalimeni**
Also update Go to 1.20.7 in the Dockerfile. It was updated in CI as part of https://github.com/hashicorp/consul-dataplane/pull/227.

1.1.x PR: https://github.com/hashicorp/consul-dataplane/pull/236
1.0.x PR: https://github.com/hashicorp/consul-dataplane/pull/237

### CODE REVIEW

**Comment by zalimeni** [comment]
@skpratt it looks like we only have `1.26.2` published for the [hashicorp/envoy-fips](https://hub.docker.com/r/hashicorp/envoy-fips/tags) image. Is that expected r/n? I see 

> If the FIPS patch release from Hashicorp is not available, reach out to the ZTS team.

in your release guide updates so maybe something you anticipated 😄 

```
ERROR: failed to solve: hashicorp/envoy-fips:v1.26.4: docker.io/hashicorp/envoy-fips:v1.26.4: not found
Error: Process completed with exit code 1.
```

**Comment by skpratt** [comment]
> @skpratt it looks like we only have `1.26.2` published for the [hashicorp/envoy-fips](https://hub.docker.com/r/hashicorp/envoy-fips/tags) image. Is that expected r/n? I see
> 
> > If the FIPS patch release from Hashicorp is not available, reach out to the ZTS team.
> 
> in your release guide updates so maybe something you anticipated 😄
> 
> ```
> ERROR: failed to solve: hashicorp/envoy-fips:v1.26.4: docker.io/hashicorp/envoy-fips:v1.26.4: not found
> Error: Process completed with exit code 1.
> ```

Yeah, we can either merge this without the FIPS version bump (and I can follow up after envoy-fips:1.26.4 is out - estimating EOD). Or we can wait until envoy-fips:1.26.4 is out.

I'll approve and let you decide.

**Review by skpratt — APPROVED** [review]
Approved to either wait for FIPS image or to remove FIPS image update (which I am happy to do separately)

**Comment by zalimeni** [comment]
Thanks @skpratt ! Sounds like that will probably be available soon, so I'm happy to leave the PR open. Feel free to re-run tests and merge when you're ready.

**Pull request merged**
